name: Get App Configuration

on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
        description: "Name of the app service"
      resourceGroupName:
        required: true
        type: string
        description: "Resource group containing the app service"
      environment:
        required: true
        type: string
        description: "Environment (dev, qa, prod)"
      type:
        required: true
        type: string
        description: "Type of the app service (webapp, functionapp)"
    secrets:
      AZURE_CREDENTIALS:
        required: true
        description: "Azure credentials for authentication"

jobs:
  get-app-config:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Get App Configuration
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Getting configuration for ${{ inputs.type }} ${{ inputs.appName }} in ${{ inputs.resourceGroupName }} (${{ inputs.environment }})"
            timestamp=$(date +%Y%m%d_%H%M%S)
            output_file="${{ inputs.appName }}_config_${timestamp}.json"
            
            if [ "${{ inputs.type }}" == "webapp" ]; then
              az webapp config appsettings list --name ${{ inputs.appName }} --resource-group ${{ inputs.resourceGroupName }} > "$output_file"
            elif [ "${{ inputs.type }}" == "functionapp" ]; then
              az functionapp config appsettings list --name ${{ inputs.appName }} --resource-group ${{ inputs.resourceGroupName }} > "$output_file"
            else
              echo "Unsupported app type: ${{ inputs.type }}"
              exit 1
            fi
            
            echo "Configuration successfully retrieved and saved to $output_file"
            echo "Configuration contents:"
            cat "$output_file"
      
      - name: Upload Configuration as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-config-${{ inputs.appName }}-${{ github.run_id }}
          path: ${{ inputs.appName }}_config_*.json
          retention-days: 7