name: Restart App Service

on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
        description: "Name of the app service"
      resourceGroupName:
        required: true
        type: string
        description: "Resource group containing the app service"
      environment:
        required: true
        type: string
        description: "Environment (dev, qa, prod)"
      type:
        required: true
        type: string
        description: "Type of the app service (webapp, functionapp)"

jobs:
  restart-app-service:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Restart App Service
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Restarting ${{ inputs.type }} ${{ inputs.appName }} in ${{ inputs.resourceGroupName }} (${{ inputs.environment }})"
            if [ "${{ inputs.type }}" == "webapp" ]; then
              az webapp restart --name ${{ inputs.appName }} --resource-group ${{ inputs.resourceGroupName }}
            elif [ "${{ inputs.type }}" == "functionapp" ]; then
              az functionapp restart --name ${{ inputs.appName }} --resource-group ${{ inputs.resourceGroupName }}
            else
              echo "Unsupported app type: ${{ inputs.type }}"
              exit 1
            fi
            echo "App service restarted successfully"
      
      - name: Upload Log as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: restart-app-service-log-${{ inputs.appName }}-${{ github.run_id }}
          path: restart-app-service-log.txt
          retention-days: 7