name: Test Dev Pipeline

on:
  workflow_dispatch:
    inputs:
      choosePipeline:
        description: 'Choose pipeline to run'
        required: true
        default: 'getConfiguration'
        type: choice
        options:
          - startApplication
          - restartApplication
          - stopApplication
          - getConfiguration
          - setConfiguration
          - delConfiguration
          - buildAndPushNewImage
          - changeImage
      filePath:
        description: '[=] setConfiguration only. The path to the file itself from root of directory (foo/bar/configuration.yaml)'
        required: false
        default: 'configuration/athena-lg-applications/settings.DEV.json'
        type: string
      settingsToDelete:
        description: '[=] delConfiguration only. The settings you want to remove space seperated like (FOO hello)'
        required: false
        default: ' '
        type: string
      imageDetails:
        description: '[=] For buildAndPushNewImage/changeImage. Format: "imageRepositoryAndTag|dockerfilePath|changeImageOnWebapp" (e.g. "ai/dual-graphs:v1|Dockerfile|true")'
        required: false
        default: 'ai/dual-graphs-athena-lg:test-langgraph-explorer|Dockerfile|false'
        type: string
      appName:
        description: 'Application name'
        required: true
        type: string
      resourceGroupName:
        description: 'Resource group name'
        required: true
        type: string
      type:
        description: 'Application type (webapp, functionapp)'
        required: true
        default: 'webapp'
        type: string
      environment:
        description: 'Environment (dev, qa, prod)'
        required: true
        default: 'dev'
        type: string
      containerRegistries:
        description: 'Container registries: "devRegistryName|qaRegistryName"'
        required: true
        type: string

jobs:
  ### APPLICATION ###
  start-application:
    if: ${{ github.event.inputs.choosePipeline == 'startApplication' }}
    uses: ./.github/workflows/app-service-start.yaml
    with:
      appName: ${{ github.event.inputs.appName }}
      environment: ${{ github.event.inputs.environment }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      type: ${{ github.event.inputs.type }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  restart-application:
    if: ${{ github.event.inputs.choosePipeline == 'restartApplication' }}
    uses: ./.github/workflows/app-service-restart.yaml
    with:
      appName: ${{ github.event.inputs.appName }}
      environment: ${{ github.event.inputs.environment }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      type: ${{ github.event.inputs.type }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  stop-application:
    if: ${{ github.event.inputs.choosePipeline == 'stopApplication' }}
    uses: ./.github/workflows/app-service-stop.yaml
    with:
      appName: ${{ github.event.inputs.appName }}
      environment: ${{ github.event.inputs.environment }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      type: ${{ github.event.inputs.type }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  ### CONFIGURATION ###
  get-configuration:
    if: ${{ github.event.inputs.choosePipeline == 'getConfiguration' }}
    uses: ./.github/workflows/app-get-config.yaml
    with:
      appName: ${{ github.event.inputs.appName }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      environment: ${{ github.event.inputs.environment }}
      type: ${{ github.event.inputs.type }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  set-configuration:
    if: ${{ github.event.inputs.choosePipeline == 'setConfiguration' }}
    uses: ./.github/workflows/app-set-config.yaml
    with:
      appName: ${{ github.event.inputs.appName }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      environment: ${{ github.event.inputs.environment }}
      filePath: ${{ github.event.inputs.filePath }}
      type: ${{ github.event.inputs.type }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  delete-configuration:
    if: ${{ github.event.inputs.choosePipeline == 'delConfiguration' }}
    uses: ./.github/workflows/app-delete-config.yaml
    with:
      appName: ${{ github.event.inputs.appName }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      environment: ${{ github.event.inputs.environment }}
      type: ${{ github.event.inputs.type }}
      settingNames: ${{ github.event.inputs.settingsToDelete }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  build-and-push-image:
    if: ${{ github.event.inputs.choosePipeline == 'buildAndPushNewImage' }}
    uses: ./.github/workflows/build-and-push-image-to-acrs.yaml
    with:
      appName: ${{ github.event.inputs.appName }}
      environment: ${{ github.event.inputs.environment }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      devContainerRegistry: ${{ fromJSON(format('["{{0}}", "{{1}}"]', split(github.event.inputs.containerRegistries, '|')[0], '')) }}
      qaContainerRegistry: ${{ fromJSON(format('["{{0}}", "{{1}}"]', split(github.event.inputs.containerRegistries, '|')[1], '')) }}
      changeImageOnWebapp: ${{ fromJSON(format('["{{0}}", "{{1}}"]', split(github.event.inputs.imageDetails, '|')[2], 'false')) }}
      imageRepositoryAndTag: ${{ fromJSON(format('["{{0}}", "{{1}}"]', split(github.event.inputs.imageDetails, '|')[0], '')) }}
      dockerFile: ${{ fromJSON(format('["{{0}}", "{{1}}"]', split(github.event.inputs.imageDetails, '|')[1], 'Dockerfile')) }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      DEV_ACR_PASSWORD: ${{ secrets.DEV_ACR_PASSWORD }}
      QA_ACR_PASSWORD: ${{ secrets.QA_ACR_PASSWORD }}

  change-image:
    if: ${{ github.event.inputs.choosePipeline == 'changeImage' }}
    uses: ./.github/workflows/change-image.yaml
    with:
      appName: ${{ github.event.inputs.appName }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      imageName: ${{ fromJSON(format('["{{0}}", "{{1}}"]', split(github.event.inputs.imageDetails, '|')[0], '')) }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
